name: Release

on:
    push:
        branches:
            - main
    workflow_dispatch: # allow manual trigger if needed

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            id-token: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"
                  registry-url: "https://registry.npmjs.org/"

            - name: Install dependencies
              run: npm ci

            - name: Run CI checks
              run: npm run ci

            - name: Create Release PR or Publish
              uses: changesets/action@v1
              with:
                  version: npm run release:version
                  publish: npm run release:publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
